[package]
name = "rust-graph-layouts"
version = "0.1.0"
edition = "2024"

[dependencies]
plotters = "0.3.7"
rand = "0.9.2"
regex = "1.11.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
